/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Ingreso;
import java.util.ArrayList;
import Modelo.*;
import ModeloDAO.UsuariosDAO;
import javax.swing.JOptionPane;
import Servicios.RegistroCuentaNueva;

/**
 *
 * @author GoodF
 */
public class CrearCuenta extends javax.swing.JFrame {

    private boolean validador = false;
    

    public boolean getValidador() {
        return validador;
    }

    public void setValidador(boolean validador) {
        this.validador = validador;
    }
    
    
    public CrearCuenta() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); // Evita que se cierre toda la app
        setLocationRelativeTo(null); // ubicando en el centro
        
        // animacion de botonos (inicia oculto)
        guardar.setVisible(false);
        salir.setVisible(false);
        borrar.setVisible(false);
        
        //secuencia para llenar permisos (primero false para evitar adelantarse)
        btVentas.setEnabled(false);
        btAlmacen.setEnabled(false);
        btCliente.setEnabled(false);
        btReporte.setEnabled(false);
        btAdministrar.setEnabled(false);
        
        //secuencia para llenar preguntas (primero false para evitar adelantarse)  
        pregunta1.setEnabled(false);
        pregunta2.setEnabled(false);
        pregunta3.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        pregunta2 = new javax.swing.JTextField();
        pregunta3 = new javax.swing.JTextField();
        pregunta1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        passw = new javax.swing.JPasswordField();
        cpassw = new javax.swing.JPasswordField();
        cargos = new javax.swing.JComboBox<>();
        btAdministrar = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        guardar = new javax.swing.JLabel();
        borrar = new javax.swing.JLabel();
        salir = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jlabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btAlmacen = new javax.swing.JCheckBox();
        btVentas = new javax.swing.JCheckBox();
        btReporte = new javax.swing.JCheckBox();
        btCliente = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        user = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Verificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 90, -1));

        pregunta2.setBackground(new java.awt.Color(255, 255, 255));
        pregunta2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(pregunta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 210, -1));

        pregunta3.setBackground(new java.awt.Color(255, 255, 255));
        pregunta3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pregunta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pregunta3ActionPerformed(evt);
            }
        });
        getContentPane().add(pregunta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 210, -1));

        pregunta1.setBackground(new java.awt.Color(255, 255, 255));
        pregunta1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(pregunta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 210, -1));

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("¿Cuál fue tu primer trabajo?");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, -1, -1));

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("¿Cómo se llamaba tu abuelo/a favorito/a?");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, -1));

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("¿Cuál era el nombre de tu escuela primaria?");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Responda las siguiente preguntas de seguridad:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Cargo:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 560, 10));

        passw.setBackground(new java.awt.Color(255, 255, 255));
        passw.setForeground(new java.awt.Color(0, 0, 0));
        passw.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(passw, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 150, -1));

        cpassw.setBackground(new java.awt.Color(255, 255, 255));
        cpassw.setForeground(new java.awt.Color(0, 0, 0));
        cpassw.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(cpassw, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 150, -1));

        cargos.setBackground(new java.awt.Color(255, 255, 255));
        cargos.setForeground(new java.awt.Color(0, 0, 0));
        cargos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(Seleccion el cargo)", "Gerente", "Administrador", "Vendedor", "Tecnico", "Contador", " " }));
        cargos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cargosMouseClicked(evt);
            }
        });
        getContentPane().add(cargos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 150, -1));

        btAdministrar.setForeground(new java.awt.Color(0, 0, 0));
        btAdministrar.setText("Administrar Cuentas");
        btAdministrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdministrarActionPerformed(evt);
            }
        });
        getContentPane().add(btAdministrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Confirmar C:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, -1, -1));

        guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/guardar-creacion-2.PNG"))); // NOI18N
        guardar.setText("guardar");
        guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                guardarMouseExited(evt);
            }
        });
        getContentPane().add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 80, 80));

        borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/borrar-creacion-2.PNG"))); // NOI18N
        borrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                borrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                borrarMouseExited(evt);
            }
        });
        getContentPane().add(borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 80, 80));

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/salida-creacion-2.PNG"))); // NOI18N
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirMouseExited(evt);
            }
        });
        salir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                salirKeyPressed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 90, 90));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/borrar-creacion-1.PNG"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 60, 80));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/guardar-creacion-1.PNG"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, 60, -1));

        jlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/salida-creacion-1.PNG"))); // NOI18N
        jlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabelMouseEntered(evt);
            }
        });
        jlabel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jlabelKeyPressed(evt);
            }
        });
        getContentPane().add(jlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 60, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 250, 10));

        btAlmacen.setBackground(new java.awt.Color(255, 255, 255));
        btAlmacen.setForeground(new java.awt.Color(0, 0, 0));
        btAlmacen.setText("Almacen");
        btAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlmacenActionPerformed(evt);
            }
        });
        getContentPane().add(btAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, -1, -1));

        btVentas.setBackground(new java.awt.Color(255, 255, 255));
        btVentas.setForeground(new java.awt.Color(0, 0, 0));
        btVentas.setText("Realizar Ventas");
        getContentPane().add(btVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        btReporte.setBackground(new java.awt.Color(255, 255, 255));
        btReporte.setForeground(new java.awt.Color(0, 0, 0));
        btReporte.setText("Ver Reporte");
        btReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReporteActionPerformed(evt);
            }
        });
        getContentPane().add(btReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));

        btCliente.setBackground(new java.awt.Color(255, 255, 255));
        btCliente.setForeground(new java.awt.Color(0, 0, 0));
        btCliente.setText("Clientes y Proveedores");
        btCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Permisos:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        nombre.setBackground(new java.awt.Color(255, 255, 255));
        nombre.setForeground(new java.awt.Color(0, 0, 0));
        nombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 150, -1));

        user.setBackground(new java.awt.Color(255, 255, 255));
        user.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 150, -1));

        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("*Incluir al menos un numero, una letra mayuscula y minuscula");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("*Debe tener un minimo de 7 y maximo 15 caracteres");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("*Debe tener minimo 5 y maximo 10 caracteres");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Contraseña:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Usuario:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondos/fond - crear cuenta 2.PNG"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed

    }//GEN-LAST:event_nombreActionPerformed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void jlabelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jlabelKeyPressed
        
    }//GEN-LAST:event_jlabelKeyPressed

    private void salirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salirKeyPressed
        Login regresar = new Login();
        regresar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_salirKeyPressed

    private void jlabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabelMouseEntered
        salir.setVisible(true);
    }//GEN-LAST:event_jlabelMouseEntered

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        guardar.setVisible(true);
    }//GEN-LAST:event_jLabel9MouseEntered

    private void borrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrarMouseEntered
        
    }//GEN-LAST:event_borrarMouseEntered

    private void salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseExited
        salir.setVisible(false);
    }//GEN-LAST:event_salirMouseExited

    private void borrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrarMouseExited
        borrar.setVisible(false);
    }//GEN-LAST:event_borrarMouseExited

    private void guardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarMouseExited
        guardar.setVisible(false);
    }//GEN-LAST:event_guardarMouseExited

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        borrar.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseEntered

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
            Login tec = new Login();
            tec.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_salirMouseClicked

    private void btAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlmacenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAlmacenActionPerformed

    private void btReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btReporteActionPerformed

    private void btClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btClienteActionPerformed

    private void guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarMouseClicked
 
        RegistroCuentaNueva conector = new RegistroCuentaNueva();
        UsuariosDAO conector2 = new UsuariosDAO();
            //Pedidos = 
            ArrayList<Permisos> mispermisos = new ArrayList<>();
            mispermisos = conector.recolentadoPermisos(0, btVentas.isSelected(), btAlmacen.isSelected(), btCliente.isSelected(), btReporte.isSelected(), btAdministrar.isSelected());
            
            ArrayList<Preguntas> mispreguntas = new ArrayList<>();
            mispreguntas = conector.recolentadoRespuestas(0, pregunta1.getText(), pregunta2.getText(), pregunta3.getText(), 1, 2, 3);
            
            Cargos micargo = new Cargos();
            micargo.setId_cargo(cargos.getSelectedIndex());
       
        if((conector.verificarRegistroUsuario(user.getText(), passw.getText(), cpassw.getText(), nombre.getText(),cargos.getSelectedIndex())) == null && !mispermisos.isEmpty() && !mispreguntas.isEmpty()) { //Empty: validar que el array este vacio - !: no este vacio // validando todas las condiciones
           // verificar devuelve String, si no hay string es porque no hay datos, esta libre, puede usarse
            
           Usuarios myuser = new Usuarios(0, nombre.getText(), user.getText(), passw.getText(),micargo,mispreguntas,mispermisos);

           if (conector2.insertar(myuser)){
                           JOptionPane.showMessageDialog(null, "Felicidades "+myuser.getNombre()+"! Te haz registrado con exito.", 
                              "Registro", JOptionPane.INFORMATION_MESSAGE);
                           this.dispose();
            }else{
                        JOptionPane.showMessageDialog(null, "No se ha podido completar el registro, intentelo mas tarde", 
                              "Registro_Error", JOptionPane.ERROR_MESSAGE);
            }
           
        }
    }//GEN-LAST:event_guardarMouseClicked

    private void btAdministrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdministrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAdministrarActionPerformed

    private void borrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrarMouseClicked
        
            // Restableciendo todos los valores a predeterminado
            
        cargos.setSelectedIndex(0);
        nombre.setText(null);
        passw.setText(null);
        user.setText(null);
        cpassw.setText(null);
        
        btVentas.setEnabled(false);
        btAlmacen.setEnabled(false);
        btCliente.setEnabled(false);
        btReporte.setEnabled(false);
        btAdministrar.setEnabled(false);
        btVentas.setSelected(false);
        btAlmacen.setSelected(false);
        btCliente.setSelected(false);
        btReporte.setSelected(false);
        btAdministrar.setSelected(false);
        
        pregunta1.setText("");
        pregunta2.setText("");
        pregunta3.setText("");
        
        pregunta1.setEnabled(false);
        pregunta2.setEnabled(false);
        pregunta3.setEnabled(false);
                                      
        
    }//GEN-LAST:event_borrarMouseClicked

    private void pregunta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pregunta3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pregunta3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Servicios.RegistroCuentaNueva verificador = new Servicios.RegistroCuentaNueva();
 
        btVentas.setEnabled(false);
        btAlmacen.setEnabled(false);
        btCliente.setEnabled(false);
        btReporte.setEnabled(false);
        btAdministrar.setEnabled(false);
        btVentas.setSelected(false);
        btAlmacen.setSelected(false);
        btCliente.setSelected(false);
        btReporte.setSelected(false);
        btAdministrar.setSelected(false);
        
        String respuesta = verificador.verificarRegistroUsuario(user.getText(), passw.getText(), cpassw.getText(), nombre.getText(),cargos.getSelectedIndex());
        if(respuesta ==null){ /*Linea en conflicto*/
            
            //Permite editar las preguntas - respuestas
            pregunta1.setEnabled(true);
            pregunta2.setEnabled(true);
            pregunta3.setEnabled(true);
                pregunta3.requestFocus();
            //Permite editar los permisos de acuerdo al cargo
            
            switch (cargos.getSelectedIndex()){
                case 1: btVentas.setEnabled(true);
                        btAlmacen.setEnabled(true);
                        btCliente.setEnabled(true);
                        btReporte.setEnabled(true);
                        break;
                case 2: btVentas.setEnabled(true);
                        btAlmacen.setEnabled(true);
                        btCliente.setEnabled(true);
                        btReporte.setEnabled(true);
                        btAdministrar.setEnabled(true); 
                        break;
                case 3: btVentas.setEnabled(true);
                        btAlmacen.setEnabled(true);
                        btCliente.setEnabled(true);
                        btReporte.setEnabled(true);
                        break;
                case 4: btVentas.setEnabled(true);
                        btAlmacen.setEnabled(true);
                        btCliente.setEnabled(true);
                        break;
                case 5: btReporte.setEnabled(true);
                        btAlmacen.setEnabled(true);
                        break;
            }
            }else{
                JOptionPane.showMessageDialog(rootPane, respuesta);
            }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cargosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cargosMouseClicked
        btVentas.setEnabled(false);
        btAlmacen.setEnabled(false);
        btCliente.setEnabled(false);
        btReporte.setEnabled(false);
        btAdministrar.setEnabled(false);
        btVentas.setSelected(false);
        btAlmacen.setSelected(false);
        btCliente.setSelected(false);
        btReporte.setSelected(false);
        btAdministrar.setSelected(false);
        
        pregunta1.setText("");
        pregunta2.setText("");
        pregunta3.setText("");
        
        pregunta1.setEnabled(false);
        pregunta2.setEnabled(false);
        pregunta3.setEnabled(false);
    }//GEN-LAST:event_cargosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel borrar;
    private javax.swing.JCheckBox btAdministrar;
    private javax.swing.JCheckBox btAlmacen;
    private javax.swing.JCheckBox btCliente;
    private javax.swing.JCheckBox btReporte;
    private javax.swing.JCheckBox btVentas;
    private javax.swing.JComboBox<String> cargos;
    private javax.swing.JPasswordField cpassw;
    private javax.swing.JLabel guardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jlabel;
    private javax.swing.JTextField nombre;
    private javax.swing.JPasswordField passw;
    private javax.swing.JTextField pregunta1;
    private javax.swing.JTextField pregunta2;
    private javax.swing.JTextField pregunta3;
    private javax.swing.JLabel salir;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
