/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Ingreso;

import ModeloDAO.UsuariosDAO;
import Modelo.Usuarios;
import java.awt.Color;
import java.util.Arrays;
import javax.swing.JOptionPane;
import Seguridad.Sesion;

/**
 *
 * @author GoodF
 */
public class Login extends javax.swing.JFrame {

    private int intentos = 3;

    public int getIntentos() {
        return intentos;
    }

    public void setIntentos(int intentos) {
        this.intentos = intentos;
    }

    public Login() {
        initComponents();
        setLocationRelativeTo(null); // ubicando en el centro el login

        //Animaciones de colores para minimizar, ampliar y cerrar
        botoncerrar.setVisible(false);
        Ampliar.setVisible(false);
        minimizar.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        minimizar = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Ampliar = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        botoncerrar = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        usuario = new javax.swing.JTextField();
        IniciarSesion = new javax.swing.JButton();
        Crear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/minimizar 2 icono.PNG"))); // NOI18N
        minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizarMouseExited(evt);
            }
        });
        getContentPane().add(minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 0, 30, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/minimizar 1 icono.PNG"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 8, 20, 10));

        Ampliar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/ampliar 2 icono.PNG"))); // NOI18N
        Ampliar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AmpliarMouseExited(evt);
            }
        });
        getContentPane().add(Ampliar, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, -2, 30, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/amplicar 1 icono.PNG"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 2, 20, -1));

        botoncerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/cerrar 2 icono.PNG"))); // NOI18N
        botoncerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botoncerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botoncerrarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botoncerrarMouseExited(evt);
            }
        });
        getContentPane().add(botoncerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/cerrar 1 icono.PNG"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/diseno/linea borde.PNG"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, -1));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 210, 10));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 210, 10));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Olvido su contraseña?");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 150, 10));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/usuario iconoo.PNG"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 60, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/password iconoo.PNG"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 50, 50));

        password.setBackground(new java.awt.Color(0, 112, 192));
        password.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setText("jPasswordField1");
        password.setBorder(null);
        password.setCaretColor(new java.awt.Color(255, 255, 255));
        password.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordMouseClicked(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 210, 30));

        usuario.setBackground(new java.awt.Color(0, 112, 192));
        usuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usuario.setForeground(new java.awt.Color(255, 255, 255));
        usuario.setText("Ingrese el usuario");
        usuario.setBorder(null);
        usuario.setCaretColor(new java.awt.Color(255, 255, 255));
        usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usuarioMouseClicked(evt);
            }
        });
        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 210, 30));

        IniciarSesion.setBackground(new java.awt.Color(255, 153, 0));
        IniciarSesion.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        IniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        IniciarSesion.setText("Iniciar sesion");
        IniciarSesion.setBorder(null);
        IniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IniciarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IniciarSesionMouseExited(evt);
            }
        });
        IniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(IniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, 210, 30));

        Crear.setBackground(new java.awt.Color(153, 153, 153));
        Crear.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Crear.setForeground(new java.awt.Color(255, 255, 255));
        Crear.setText("Crear cuenta");
        Crear.setBorder(null);
        Crear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CrearMouseEntered(evt);
            }
        });
        Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearActionPerformed(evt);
            }
        });
        getContentPane().add(Crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, 120, 30));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bienvenido!");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 320, 50));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondos/fondo login 2.PNG"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-48, 9, 930, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearActionPerformed
        setIntentos(4);
        CrearCuenta conexcion = new CrearCuenta();
        conexcion.setVisible(true);
    }//GEN-LAST:event_CrearActionPerformed

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioActionPerformed

    private void IniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarSesionActionPerformed
        char[] pass = password.getPassword(); //arreglo de char
        String mipassword = new String(pass); //insertado en String - mayor seguridad que un getText

        UsuariosDAO verificaIdentidad = new UsuariosDAO();

        Usuarios usuarioValido = verificaIdentidad.Login(usuario.getText(), mipassword);

        Arrays.fill(pass, '0'); // limpiar el arreglo por seguridad

        if (usuarioValido != null) {
            Sesion.iniciarSesion(usuarioValido);
            Ventana_Principal ingresoApp = new Ventana_Principal();
            ingresoApp.setVisible(true);
            this.setVisible(false);
        } else {
            // Reducimos el contador de intentos
            setIntentos(getIntentos() - 1);

            if (getIntentos() > 0) {
                JOptionPane.showMessageDialog(this,
                        "Usuario o Contraseña Incorrecta. Intentos restantes: " + getIntentos(),
                        "Error", JOptionPane.WARNING_MESSAGE);
                password.setText(null);
                usuario.setText(null);
                usuario.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this,
                        "¡Has superado el límite de intentos! Inténtalo más tarde.",
                        "Error", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
            }
        }

    }//GEN-LAST:event_IniciarSesionActionPerformed

    private void usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarioMouseClicked
        usuario.setText(null);
        //usuario.setForeground(Color.black);
    }//GEN-LAST:event_usuarioMouseClicked

    private void passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseClicked
        password.setText(null);
        //password.setForeground(Color.black);

    }//GEN-LAST:event_passwordMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        setIntentos(3);
        RecuperarCuenta recuperar = new RecuperarCuenta();
        recuperar.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void IniciarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniciarSesionMouseEntered
        IniciarSesion.setBackground(new Color(255, 204, 0));
    }//GEN-LAST:event_IniciarSesionMouseEntered

    private void IniciarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniciarSesionMouseExited
        IniciarSesion.setBackground(new Color(255, 153, 0));
    }//GEN-LAST:event_IniciarSesionMouseExited

    private void CrearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearMouseEntered

    }//GEN-LAST:event_CrearMouseEntered

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        jLabel7.setVisible(false);
        botoncerrar.setVisible(true);
    }//GEN-LAST:event_jLabel7MouseEntered

    private void botoncerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botoncerrarMouseExited
        botoncerrar.setVisible(false);
        jLabel7.setVisible(true);
    }//GEN-LAST:event_botoncerrarMouseExited

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        Ampliar.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseEntered

    private void AmpliarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AmpliarMouseExited
        Ampliar.setVisible(false);
    }//GEN-LAST:event_AmpliarMouseExited

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        minimizar.setVisible(true);
    }//GEN-LAST:event_jLabel9MouseEntered

    private void minimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseExited
        minimizar.setVisible(false);
    }//GEN-LAST:event_minimizarMouseExited

    private void botoncerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botoncerrarMouseClicked
        System.exit(0); // cerrar el programa
    }//GEN-LAST:event_botoncerrarMouseClicked

    private void minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseClicked
        setState(Login.ICONIFIED);
    }//GEN-LAST:event_minimizarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ampliar;
    private javax.swing.JButton Crear;
    private javax.swing.JButton IniciarSesion;
    private javax.swing.JLabel botoncerrar;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel minimizar;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
