package Vista.Ingreso;

import javax.swing.JOptionPane;
import ModeloDAO.UsuariosDAO;
import Modelo.Usuarios;
import Servicios.RecuperarCuenta;

public class RecuperarCuenta_Contrasena extends javax.swing.JFrame {

    Usuarios user;

    public RecuperarCuenta_Contrasena(String usuario) {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); // Evita que se cierre toda la app

        UsuariosDAO conec = new UsuariosDAO();
        user = conec.listarUno(usuario);
        //Datos para el usuario

        saludo.setText("Hola " + user.getNombre() + "! ");
        passActual.setText(user.getPassword());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cambiarContrasena = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        passActual = new javax.swing.JTextField();
        nuevaPass = new javax.swing.JPasswordField();
        cnuevaPass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        saludo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("*Incluir al menos un numero, una letra mayuscula y minuscula");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("*Debe tener un minimo de 8 y maximo 15 caracteres");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 380, -1));

        cambiarContrasena.setBackground(new java.awt.Color(153, 0, 0));
        cambiarContrasena.setForeground(new java.awt.Color(255, 255, 255));
        cambiarContrasena.setText("Cambiar contraseña");
        cambiarContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarContrasenaActionPerformed(evt);
            }
        });
        getContentPane().add(cambiarContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, -1, -1));

        salir.setBackground(new java.awt.Color(0, 102, 204));
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setText("Cancelar");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 110, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 330, 10));

        passActual.setEditable(false);
        passActual.setBackground(new java.awt.Color(255, 255, 255));
        passActual.setForeground(new java.awt.Color(0, 0, 0));
        passActual.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(passActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 130, -1));

        nuevaPass.setBackground(new java.awt.Color(255, 255, 255));
        nuevaPass.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(nuevaPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 100, -1));

        cnuevaPass.setBackground(new java.awt.Color(255, 255, 255));
        cnuevaPass.setForeground(new java.awt.Color(0, 0, 0));
        cnuevaPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnuevaPassActionPerformed(evt);
            }
        });
        getContentPane().add(cnuevaPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 130, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Confirmar C:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Contraseña nueva:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Contraseña actual: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        saludo.setBackground(new java.awt.Color(0, 0, 0));
        saludo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        saludo.setForeground(new java.awt.Color(0, 0, 0));
        saludo.setText("Hola");
        getContentPane().add(saludo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 110, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondos/recuperacion.PNG"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cnuevaPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnuevaPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnuevaPassActionPerformed

    private void cambiarContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarContrasenaActionPerformed
        RecuperarCuenta verificame = new RecuperarCuenta(); // Llamando para obtener el metodo verificador
        UsuariosDAO conexion = new UsuariosDAO();
        //Verificacion si se admite un cambio de contrasena
        
        if (verificame.autorizadordeCambiodePassword(nuevaPass.getText(), cnuevaPass.getText())) { // Llamando a mi verificador para corroborar los requisitos del password
            user.setPassword(cnuevaPass.getText());// Contrasena asignada
            conexion.actualizar(user);
            JOptionPane.showMessageDialog(null, "Cambio Exitoso!");
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "La contrasena no cumple con los requisitos o es diferente!", "Error en Contraseña", JOptionPane.ERROR_MESSAGE);
            nuevaPass.setText(null);
            cnuevaPass.setText(null);
            nuevaPass.requestFocus();
        }

    }//GEN-LAST:event_cambiarContrasenaActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        Login salir2 = new Login();
        salir2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecuperarCuenta_Contrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecuperarCuenta_Contrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecuperarCuenta_Contrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecuperarCuenta_Contrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecuperarCuenta_Contrasena("hola").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cambiarContrasena;
    private javax.swing.JPasswordField cnuevaPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPasswordField nuevaPass;
    private javax.swing.JTextField passActual;
    private javax.swing.JButton salir;
    private javax.swing.JLabel saludo;
    // End of variables declaration//GEN-END:variables
}
