/*
 * Click 
 * Click 
 */
package Vista.Ingreso;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author GoodF
 */
public class RecuperarCuenta extends javax.swing.JFrame {

    /**
     * Creates new form RecuperarCuenta
     */
    public RecuperarCuenta() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); // Evita que se cierre toda la app

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        preguntadeR = new javax.swing.JTextField();
        preguntasseguridad = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Validacion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, -1, 30));

        preguntadeR.setBackground(new java.awt.Color(255, 255, 255));
        preguntadeR.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        preguntadeR.setForeground(new java.awt.Color(153, 153, 153));
        preguntadeR.setText("Ingrese la respuesta");
        preguntadeR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        preguntadeR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                preguntadeRMouseClicked(evt);
            }
        });
        preguntadeR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preguntadeRActionPerformed(evt);
            }
        });
        getContentPane().add(preguntadeR, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 250, 30));

        preguntasseguridad.setBackground(new java.awt.Color(255, 255, 255));
        preguntasseguridad.setForeground(new java.awt.Color(0, 0, 0));
        preguntasseguridad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(Responda alguna pregunta de seguridad)", "¿Cuál era el nombre de tu escuela primaria?", "¿Cómo se llamaba tu abuelo/a favorito/a?", "¿Cuál fue tu primer trabajo?", " " }));
        preguntasseguridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preguntasseguridadActionPerformed(evt);
            }
        });
        getContentPane().add(preguntasseguridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 122, 290, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/password2.PNG"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 60, 40));

        usuario.setBackground(new java.awt.Color(255, 255, 255));
        usuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usuario.setForeground(new java.awt.Color(153, 153, 153));
        usuario.setText("Ingrese el usuario");
        usuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        usuario.setCaretColor(new java.awt.Color(102, 102, 102));
        usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usuarioMouseClicked(evt);
            }
        });
        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });
        usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usuarioKeyPressed(evt);
            }
        });
        getContentPane().add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 250, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/usuario 2.PNG"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 70, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondos/recuperacion.PNG"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarioMouseClicked
        usuario.setText(null);
        usuario.setForeground(Color.black);
    }//GEN-LAST:event_usuarioMouseClicked

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioActionPerformed

    private void preguntadeRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preguntadeRActionPerformed

    }//GEN-LAST:event_preguntadeRActionPerformed

    private void preguntasseguridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preguntasseguridadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_preguntasseguridadActionPerformed

    private void preguntadeRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_preguntadeRMouseClicked

        preguntadeR.setText("");
        preguntadeR.setForeground(Color.black);

    }//GEN-LAST:event_preguntadeRMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Servicios.RecuperarCuenta conector = new Servicios.RecuperarCuenta();

        if (preguntasseguridad.getSelectedIndex() > 1) {
            int verificador = conector.verificarUsuario(usuario.getText(), preguntadeR.getText(), preguntasseguridad.getSelectedIndex());
            switch (verificador) {
                case 0:
                    JOptionPane.showMessageDialog(null, "Respuesta Incorrecta!");
                    usuario.setText(null);
                    preguntadeR.setText(null);
                    preguntasseguridad.setSelectedIndex(0);
                    usuario.requestFocus();
                    break;
                case -1:
                    JOptionPane.showMessageDialog(null, "El usuario no existe!");
                    usuario.setText(null);
                    preguntadeR.setText(null);
                    preguntasseguridad.setSelectedIndex(0);
                    usuario.requestFocus();
                    break;
                default:
                    RecuperarCuenta_Contrasena trasladar = new RecuperarCuenta_Contrasena(usuario.getText());
                    trasladar.setVisible(true);
                    this.dispose();
                    break;
                    
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecciona el cargo!");
            usuario.setText(null);
            preguntadeR.setText(null);
            preguntasseguridad.setSelectedIndex(0);
            usuario.requestFocus();
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void usuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usuarioKeyPressed

    }//GEN-LAST:event_usuarioKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecuperarCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecuperarCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecuperarCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecuperarCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecuperarCuenta().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField preguntadeR;
    private javax.swing.JComboBox<String> preguntasseguridad;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
