/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Ingreso;
import Servicios.InterfazUsuarioService;
import Seguridad.Sesion;
import Modelo.Usuarios;
import Vista.Ingreso.Login;
import javax.swing.JOptionPane;
/**
 *
 * @author GoodF
 */
public class Ventana_Principal extends javax.swing.JFrame {
         
              // Set para definir los logos (rostros) segun usuario
        public void definirLogoTecnico(boolean estado){
            this.logoTecnico.setVisible(estado);
        }
        public void definirLogoVendedor(boolean estado){
            this.logoVendedor.setVisible(estado);
        }     
        public void definirLogoGerente(boolean estado){
            this.logoGerente.setVisible(estado);
        }        
        public void definirLogoContador(boolean estado){
            this.logoContador.setVisible(estado);
        }        
        public void definirLogoAdministrador(boolean estado){
            this.logoAdministrador.setVisible(estado);
        }
        
            //Set para definir los iconos de permisos segun usuarios
        public void setIconSinAccesoClientes(boolean estado){
            this.sinAccesoClientes.setVisible(estado);
        }
        public void setIconSinAccesoVentas(boolean estado){
            this.sinAccesoVentas.setVisible(estado);
        }
        public void setIconSinAccesoAlmacen(boolean estado){
            this.sinAccesoAlmacen.setVisible(estado);
        }
        public void setIconSinAccesoReporte(boolean estado){
            this.sinAccesoReporte.setVisible(estado);
        }
        public void setIconSinAccesoAdministrar(boolean estado){
            this.sinAccesoAdministrar.setVisible(estado);
        }
        
            //Set para definir los botones de permisos segun usuarios
        public void setBotonClientes(boolean estado){
            this.botonClientes.setVisible(estado);
        }
        public void setBotonVentas(boolean estado){
            this.botonVentas.setVisible(estado);
        }
        public void setBotonAlmacen(boolean estado){
            this.botonAlmacen.setVisible(estado);
        }
        public void setBotonReporte(boolean estado){
            this.botonReporte.setVisible(estado);
        }
        public void setBotonAdministar(boolean estado){
            this.botonAdministrar.setVisible(estado);
        }
      
    public Ventana_Principal() {
        
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); // Evita que se cierre toda la app

        
        //Usuario sesion:
        Usuarios myuser= Sesion.getUsuarioActual();
        
        if(myuser == null){
            JOptionPane.showMessageDialog(rootPane, "Error! Ningun Usuario se ha logeado!");
            Login volver = new Login();
            volver.setVisible(true);
            this.dispose();
        }
        InterfazUsuarioService.logosUsuariosDefaults(this); // Oculta todos los logos
        InterfazUsuarioService.iconosPermisosDefaults(this); // Mostrando todos los iconos de permisos denegados (tuve problemas con la instanciacion desde el AppClass)
        
        InterfazUsuarioService.logoUserApp(this,myuser.getLosCargos().getId_cargo());  // Definiendo el logo de acuerdo al cargo ( no se debe instanciar para mantener el valor
           //Muestra solo del usuario que hemos seleccionado
        
           for (int i = 0; i < myuser.getLosPermisos().size(); i++) {
                    InterfazUsuarioService.iconosPermisosUsuarios(this, myuser.getLosPermisos().get(i).getId_permiso());
        }
        
        //Animacion de iconos salida al inicio  y configuracion de cuenta
        salirAlInicio.setVisible(false);
        configuraMiCuenta.setVisible(false);
        
        //animacion botones permisos:
        botonGoReportes.setVisible(false);
        botonGoAlmacen.setVisible(false);
        botonGoVentas.setVisible(false);
        botonGoClientes.setVisible(false);
        
        
        //animacion botones (cerrar, minim, maxim)
        botonGoCerrar.setVisible(false);
        botonGoMinimizar.setVisible(false);
        botonGoMaximizar.setVisible(false);
        
        //Presentacion
        ElCargo.setText(myuser.getLosCargos().getNombre_Cargo());
        Presentacion.setText("Bienvenido "+myuser.getNombre()+"!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ElCargo = new javax.swing.JLabel();
        Presentacion = new javax.swing.JLabel();
        botonGoMinimizar = new javax.swing.JLabel();
        botonGoCerrar = new javax.swing.JLabel();
        botonGoMaximizar = new javax.swing.JLabel();
        botonMinimizar = new javax.swing.JLabel();
        botonelCerrar = new javax.swing.JLabel();
        botonMaximizar = new javax.swing.JLabel();
        botonGoClientes = new javax.swing.JLabel();
        botonGoReportes = new javax.swing.JLabel();
        botonGoAlmacen = new javax.swing.JLabel();
        botonGoVentas = new javax.swing.JLabel();
        configuraMiCuenta = new javax.swing.JLabel();
        backConfiguraMiCuenta = new javax.swing.JLabel();
        salirAlInicio = new javax.swing.JLabel();
        backSalirAlInicio = new javax.swing.JLabel();
        sinAccesoAdministrar = new javax.swing.JLabel();
        botonAdministrar = new javax.swing.JLabel();
        sinAccesoReporte = new javax.swing.JLabel();
        botonReporte = new javax.swing.JLabel();
        sinAccesoVentas = new javax.swing.JLabel();
        botonVentas = new javax.swing.JLabel();
        sinAccesoClientes = new javax.swing.JLabel();
        botonClientes = new javax.swing.JLabel();
        sinAccesoAlmacen = new javax.swing.JLabel();
        botonAlmacen = new javax.swing.JLabel();
        configuracion = new javax.swing.JLabel();
        reporte = new javax.swing.JLabel();
        almacen = new javax.swing.JLabel();
        vender = new javax.swing.JLabel();
        clientes = new javax.swing.JLabel();
        logoAdministrador = new javax.swing.JLabel();
        logoContador = new javax.swing.JLabel();
        logoTecnico = new javax.swing.JLabel();
        logoVendedor = new javax.swing.JLabel();
        logoGerente = new javax.swing.JLabel();
        backgrnd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ElCargo.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        ElCargo.setForeground(new java.awt.Color(255, 255, 255));
        ElCargo.setText("Gerente");
        getContentPane().add(ElCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, -1, -1));

        Presentacion.setFont(new java.awt.Font("Dubai", 0, 24)); // NOI18N
        Presentacion.setForeground(new java.awt.Color(0, 0, 0));
        Presentacion.setText("Bienvenido Hola!");
        getContentPane().add(Presentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        botonGoMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/minimizar 2 icono.PNG"))); // NOI18N
        botonGoMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonGoMinimizarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonGoMinimizarMouseExited(evt);
            }
        });
        getContentPane().add(botonGoMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 1, 30, -1));

        botonGoCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/cerrar 2 icono.PNG"))); // NOI18N
        botonGoCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonGoCerrarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonGoCerrarMouseExited(evt);
            }
        });
        getContentPane().add(botonGoCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 2, -1, -1));

        botonGoMaximizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/ampliar 2 icono.PNG"))); // NOI18N
        botonGoMaximizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonGoMaximizarMouseExited(evt);
            }
        });
        getContentPane().add(botonGoMaximizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 1, -1, -1));

        botonMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonMinimizarMouseEntered(evt);
            }
        });
        getContentPane().add(botonMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 20, 10));

        botonelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonelCerrarMouseEntered(evt);
            }
        });
        getContentPane().add(botonelCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 10, 10));

        botonMaximizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonMaximizarMouseEntered(evt);
            }
        });
        getContentPane().add(botonMaximizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 10, 20, 10));

        botonGoClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/AccesoIcon_Clientes.PNG"))); // NOI18N
        botonGoClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonGoClientesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonGoClientesMouseExited(evt);
            }
        });
        getContentPane().add(botonGoClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 254, 220, -1));

        botonGoReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/AccesoIcon_Reporte.PNG"))); // NOI18N
        botonGoReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonGoReportesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonGoReportesMouseExited(evt);
            }
        });
        getContentPane().add(botonGoReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 417, 230, 160));

        botonGoAlmacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/AccesoIcon_Almacen.PNG"))); // NOI18N
        botonGoAlmacen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonGoAlmacenMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonGoAlmacenMouseExited(evt);
            }
        });
        getContentPane().add(botonGoAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 423, 210, 140));

        botonGoVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/AccesoIcon_Ventas.PNG"))); // NOI18N
        botonGoVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonGoVentasMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonGoVentasMouseExited(evt);
            }
        });
        getContentPane().add(botonGoVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 259, 200, 140));

        configuraMiCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/configuracion app.PNG"))); // NOI18N
        configuraMiCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                configuraMiCuentaMouseExited(evt);
            }
        });
        getContentPane().add(configuraMiCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 572, 50, 70));

        backConfiguraMiCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backConfiguraMiCuentaMouseEntered(evt);
            }
        });
        getContentPane().add(backConfiguraMiCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 580, 50, 50));

        salirAlInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/salida-oprimida-app.PNG"))); // NOI18N
        salirAlInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirAlInicioMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirAlInicioMouseExited(evt);
            }
        });
        getContentPane().add(salirAlInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 569, -1, -1));

        backSalirAlInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backSalirAlInicioMouseEntered(evt);
            }
        });
        getContentPane().add(backSalirAlInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 580, 50, 50));

        sinAccesoAdministrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/sinAccesoIcon_Administrar.PNG"))); // NOI18N
        getContentPane().add(sinAccesoAdministrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 18, -1, -1));

        botonAdministrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAdministrarMouseClicked(evt);
            }
        });
        getContentPane().add(botonAdministrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, 100, 100));

        sinAccesoReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/sinAccesoIcon_Reporte.PNG"))); // NOI18N
        getContentPane().add(sinAccesoReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 418, -1, -1));

        botonReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonReporteMouseEntered(evt);
            }
        });
        getContentPane().add(botonReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 120, 100));

        sinAccesoVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/sinAccesoIcon_Ventas.PNG"))); // NOI18N
        getContentPane().add(sinAccesoVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 266, -1, -1));

        botonVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonVentasMouseEntered(evt);
            }
        });
        getContentPane().add(botonVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 120, 110));

        sinAccesoClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/sinAccesoIcon_Clientes.PNG"))); // NOI18N
        getContentPane().add(sinAccesoClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 270, -1, -1));

        botonClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonClientesMouseEntered(evt);
            }
        });
        getContentPane().add(botonClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 120, 110));

        sinAccesoAlmacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/sinAccesoIcon_Almacen.PNG"))); // NOI18N
        getContentPane().add(sinAccesoAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 417, -1, 140));

        botonAlmacen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonAlmacenMouseEntered(evt);
            }
        });
        getContentPane().add(botonAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 120, 110));
        getContentPane().add(configuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 30, 120, 100));
        getContentPane().add(reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 120, 110));
        getContentPane().add(almacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 120, 110));
        getContentPane().add(vender, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 120, 110));

        clientes.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                clientesAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientesMouseClicked(evt);
            }
        });
        getContentPane().add(clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 120, 110));

        logoAdministrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/logo_administrador.PNG"))); // NOI18N
        getContentPane().add(logoAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 64, -1, 120));

        logoContador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/logo_contador.PNG"))); // NOI18N
        getContentPane().add(logoContador, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 51, -1, -1));

        logoTecnico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/logo_tecnico.PNG"))); // NOI18N
        getContentPane().add(logoTecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 60, -1, -1));

        logoVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/logo_vendedor.PNG"))); // NOI18N
        getContentPane().add(logoVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 57, 130, 130));

        logoGerente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/logo_gerente.PNG"))); // NOI18N
        getContentPane().add(logoGerente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 52, 180, 140));

        backgrnd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondos/fondo - App2.PNG"))); // NOI18N
        getContentPane().add(backgrnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clientesAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_clientesAncestorAdded

    }//GEN-LAST:event_clientesAncestorAdded

    private void clientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientesMouseClicked
                //logoGerente.setVisible(true);

    }//GEN-LAST:event_clientesMouseClicked

    private void backSalirAlInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backSalirAlInicioMouseEntered
        salirAlInicio.setVisible(true); //Animacion salida
    }//GEN-LAST:event_backSalirAlInicioMouseEntered

    private void backConfiguraMiCuentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backConfiguraMiCuentaMouseEntered
        configuraMiCuenta.setVisible(true); //Animacion configurando
    }//GEN-LAST:event_backConfiguraMiCuentaMouseEntered

    private void salirAlInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirAlInicioMouseExited
        salirAlInicio.setVisible(false);
    }//GEN-LAST:event_salirAlInicioMouseExited

    private void configuraMiCuentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configuraMiCuentaMouseExited
        configuraMiCuenta.setVisible(false);
    }//GEN-LAST:event_configuraMiCuentaMouseExited

    private void salirAlInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirAlInicioMouseClicked
         // Al salir y cerrar sesion el usuario que esta seleccionado para a ser -1 osea que ningun usuario
        Login cierrasesion = new Login();
        Sesion.cerrarSesion();
        cierrasesion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_salirAlInicioMouseClicked

    private void botonReporteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonReporteMouseEntered
        botonGoReportes.setVisible(true);
    }//GEN-LAST:event_botonReporteMouseEntered

    private void botonVentasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVentasMouseEntered
        botonGoVentas.setVisible(true);
    }//GEN-LAST:event_botonVentasMouseEntered

    private void botonClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonClientesMouseEntered
        botonGoClientes.setVisible(true);
    }//GEN-LAST:event_botonClientesMouseEntered

    private void botonAlmacenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAlmacenMouseEntered
        botonGoAlmacen.setVisible(true);
    }//GEN-LAST:event_botonAlmacenMouseEntered

    private void botonGoClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGoClientesMouseExited
        botonGoClientes.setVisible(false);
    }//GEN-LAST:event_botonGoClientesMouseExited

    private void botonGoVentasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGoVentasMouseExited
        botonGoVentas.setVisible(false);
    }//GEN-LAST:event_botonGoVentasMouseExited

    private void botonGoAlmacenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGoAlmacenMouseExited
        botonGoAlmacen.setVisible(false);
    }//GEN-LAST:event_botonGoAlmacenMouseExited

    private void botonGoReportesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGoReportesMouseExited
        botonGoReportes.setVisible(false);
    }//GEN-LAST:event_botonGoReportesMouseExited

    private void botonGoVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGoVentasMouseClicked
        Vista.Aplicacion.Ventas conexion = new Vista.Aplicacion.Ventas();
        conexion.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonGoVentasMouseClicked

    private void botonGoClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGoClientesMouseClicked
        Vista.Aplicacion.Clientes conexion = new Vista.Aplicacion.Clientes();
        conexion.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonGoClientesMouseClicked

    private void botonGoAlmacenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGoAlmacenMouseClicked
        Vista.Aplicacion.Almacen conexion = new Vista.Aplicacion.Almacen();
        conexion.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonGoAlmacenMouseClicked

    private void botonGoReportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGoReportesMouseClicked
        Vista.Aplicacion.Reportes conexion = new Vista.Aplicacion.Reportes();
        conexion.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonGoReportesMouseClicked

    private void botonAdministrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAdministrarMouseClicked
        Vista.Aplicacion.Administracion conexion = new Vista.Aplicacion.Administracion();
        conexion.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonAdministrarMouseClicked

    private void botonGoCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGoCerrarMouseExited
        botonGoCerrar.setVisible(false);
    }//GEN-LAST:event_botonGoCerrarMouseExited

    private void botonGoMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGoMinimizarMouseExited
        botonGoMinimizar.setVisible(false);
    }//GEN-LAST:event_botonGoMinimizarMouseExited

    private void botonGoMaximizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGoMaximizarMouseExited
        botonGoMaximizar.setVisible(false);
    }//GEN-LAST:event_botonGoMaximizarMouseExited

    private void botonMaximizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMaximizarMouseEntered
        botonGoMaximizar.setVisible(true);
    }//GEN-LAST:event_botonMaximizarMouseEntered

    private void botonelCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonelCerrarMouseEntered
        botonGoCerrar.setVisible(true);
    }//GEN-LAST:event_botonelCerrarMouseEntered

    private void botonMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMinimizarMouseEntered
        botonGoMinimizar.setVisible(true);
    }//GEN-LAST:event_botonMinimizarMouseEntered

    private void botonGoCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGoCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_botonGoCerrarMouseClicked

    private void botonGoMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGoMinimizarMouseClicked
        setState(Login.ICONIFIED);
    }//GEN-LAST:event_botonGoMinimizarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ElCargo;
    private javax.swing.JLabel Presentacion;
    private javax.swing.JLabel almacen;
    private javax.swing.JLabel backConfiguraMiCuenta;
    private javax.swing.JLabel backSalirAlInicio;
    private javax.swing.JLabel backgrnd;
    private javax.swing.JLabel botonAdministrar;
    private javax.swing.JLabel botonAlmacen;
    private javax.swing.JLabel botonClientes;
    private javax.swing.JLabel botonGoAlmacen;
    private javax.swing.JLabel botonGoCerrar;
    private javax.swing.JLabel botonGoClientes;
    private javax.swing.JLabel botonGoMaximizar;
    private javax.swing.JLabel botonGoMinimizar;
    private javax.swing.JLabel botonGoReportes;
    private javax.swing.JLabel botonGoVentas;
    private javax.swing.JLabel botonMaximizar;
    private javax.swing.JLabel botonMinimizar;
    private javax.swing.JLabel botonReporte;
    private javax.swing.JLabel botonVentas;
    private javax.swing.JLabel botonelCerrar;
    private javax.swing.JLabel clientes;
    private javax.swing.JLabel configuraMiCuenta;
    private javax.swing.JLabel configuracion;
    private javax.swing.JLabel logoAdministrador;
    private javax.swing.JLabel logoContador;
    private javax.swing.JLabel logoGerente;
    private javax.swing.JLabel logoTecnico;
    private javax.swing.JLabel logoVendedor;
    private javax.swing.JLabel reporte;
    private javax.swing.JLabel salirAlInicio;
    private javax.swing.JLabel sinAccesoAdministrar;
    private javax.swing.JLabel sinAccesoAlmacen;
    private javax.swing.JLabel sinAccesoClientes;
    private javax.swing.JLabel sinAccesoReporte;
    private javax.swing.JLabel sinAccesoVentas;
    private javax.swing.JLabel vender;
    // End of variables declaration//GEN-END:variables
}
