/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Aplicacion;

import Seguridad.Sesion;
import Modelo.*;
import java.util.ArrayList;
import ModeloDAO.UsuariosDAO;
import Vista.Ingreso.Login;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GoodF
 */

public class Administracion extends javax.swing.JFrame {

    /**
     * Creates new form Almacen
     */
    static Usuarios usuarioSelec;
    DefaultTableModel tablaMisUsuarios = new DefaultTableModel();

    public Administracion() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); // Evita que se cierre toda la app

        crearCabecera();
        llenarTablaUsers();
        tablaUsers.setAutoResizeMode(tablaUsers.AUTO_RESIZE_OFF);
        definirTamanioColumnas();
        usuarioSelec =null;

        //Usuario sesion:
        Usuarios myuser = Sesion.getUsuarioActual();
        if (myuser == null) {
            JOptionPane.showMessageDialog(rootPane, "Error! Ningun Usuario se ha logeado!");
            Login volver = new Login();
            volver.setVisible(true);
            this.dispose();
        }

    }

    public void crearCabecera() {
        tablaMisUsuarios.addColumn("Usuario");
        tablaMisUsuarios.addColumn("Nombre");
        tablaMisUsuarios.addColumn("Contrasena");
        tablaMisUsuarios.addColumn("Cargo");
        tablaMisUsuarios.addColumn("Permisos");
        tablaMisUsuarios.addColumn("Respuestas de Seguridad");
        tablaUsers.setModel(tablaMisUsuarios);
    }

    public void llenarTablaUsers() {
        tablaMisUsuarios.setRowCount(0);

        // Iterar sobre el arreglo cables y agregar los datos a la tabla
        ArrayList<Usuarios> myUs = new ArrayList<>();
        UsuariosDAO go = new UsuariosDAO();
        myUs = go.listarTodos();
        for (int i = 0; i < myUs.size(); i++) {
            String mispermix = "";
            String mispreguntix = "";
            for (int j = 0; j < myUs.get(i).getLosPermisos().size(); j++) {
                mispermix = mispermix + myUs.get(i).getLosPermisos().get(j).getNombre_permiso() + ", ";
            }
            for (int k = 0; k < myUs.get(i).getLasPreguntas().size(); k++) {
                mispreguntix = mispreguntix + myUs.get(i).getLasPreguntas().get(k).getRespuesta() + ", ";

            }
            Object[] datos = {
                myUs.get(i).getUsuario(),
                myUs.get(i).getNombre(),
                myUs.get(i).getPassword(),
                myUs.get(i).getLosCargos().getNombre_Cargo(),
                mispermix,
                mispreguntix
            };
            tablaMisUsuarios.addRow(datos);
        }

    }

    public void definirTamanioColumnas() {
        tablaUsers.getColumnModel().getColumn(0).setPreferredWidth(120); // Usuario
        tablaUsers.getColumnModel().getColumn(1).setPreferredWidth(120); // Nombre
        tablaUsers.getColumnModel().getColumn(2).setPreferredWidth(120); // Contraseña
        tablaUsers.getColumnModel().getColumn(3).setPreferredWidth(120); // Cargo
        tablaUsers.getColumnModel().getColumn(4).setPreferredWidth(250); // Permisos
        tablaUsers.getColumnModel().getColumn(5).setPreferredWidth(300); // Preguntas
    }
    
    public void restablecerPermisos(){
            venta.setSelected(false);
            reporte.setSelected(false);
            cliente.setSelected(false);
            almacen.setSelected(false);
            administrar.setSelected(false);
    }
    
    public void restablecerTodo(){
         nombre.setText(null);
         pass.setText(null);
         user.setText(null);
         cargo.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        botonGoSalir = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        venta = new javax.swing.JRadioButton();
        reporte = new javax.swing.JRadioButton();
        cliente = new javax.swing.JRadioButton();
        almacen = new javax.swing.JRadioButton();
        administrar = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        cargo = new javax.swing.JComboBox<>();
        user = new javax.swing.JTextField();
        pass = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsers = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setBackground(new java.awt.Color(0, 102, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Actualizar");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 590, 120, 30));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(Seleccionar Pregunta)", "¿Cuál era el nombre de tu escuela primaria?", "¿Cómo se llamaba tu abuelo/a favorito/a?", "¿Cuál fue tu primer trabajo?" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 170, -1));

        botonGoSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonGoSalirMouseClicked(evt);
            }
        });
        getContentPane().add(botonGoSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 580, 50, 50));

        jTextField4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 270, -1));

        jLabel1.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Datos:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));

        nombre.setForeground(new java.awt.Color(0, 0, 0));
        nombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 100, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("User:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Password:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Permisos:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        venta.setForeground(new java.awt.Color(0, 0, 0));
        venta.setText("Realizar Ventas");
        venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventaActionPerformed(evt);
            }
        });
        getContentPane().add(venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, -1));

        reporte.setForeground(new java.awt.Color(0, 0, 0));
        reporte.setText("Ver Reportes");
        getContentPane().add(reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, -1, -1));

        cliente.setForeground(new java.awt.Color(0, 0, 0));
        cliente.setText("Clientes y Proveedores");
        getContentPane().add(cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, -1, -1));

        almacen.setForeground(new java.awt.Color(0, 0, 0));
        almacen.setText("Almacen");
        getContentPane().add(almacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 180, -1, -1));

        administrar.setForeground(new java.awt.Color(0, 0, 0));
        administrar.setText("Administrar cuentas");
        getContentPane().add(administrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Cargo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 140, -1, -1));

        jButton3.setText("Nuevo Usuario");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 250, 140, 30));

        cargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(Seleccion el cargo)", "Gerente", "Administrador", "Vendedor", "Tecnico", "Contador", " " }));
        getContentPane().add(cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 140, 120, -1));

        user.setForeground(new java.awt.Color(0, 0, 0));
        user.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 90, -1));

        pass.setForeground(new java.awt.Color(0, 0, 0));
        pass.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 110, -1));

        jButton1.setText("Editar Datos ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 150, 30));

        tablaUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaUsersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaUsers);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 660, 220));

        jButton2.setText("Eliminar Usuario");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, 140, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondos/fondo - administrar.PNG"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ventaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonGoSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGoSalirMouseClicked
        Vista.Ingreso.Ventana_Principal regresando = new Vista.Ingreso.Ventana_Principal();
        regresando.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonGoSalirMouseClicked

    private void tablaUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUsersMouseClicked
        int fila = tablaUsers.getSelectedRow();
        if (fila != -1) {
            DefaultTableModel modelo = (DefaultTableModel) tablaUsers.getModel();

            String usuario = modelo.getValueAt(fila, 0).toString();
            UsuariosDAO ok = new UsuariosDAO();
            Usuarios usuarioC = ok.listarUno(usuario);
            
            usuarioSelec = usuarioC; 

            nombre.setText(usuarioC.getNombre());
            user.setText(usuarioC.getUsuario());
            pass.setText(usuarioC.getPassword());
            cargo.setSelectedIndex(usuarioC.getLosCargos().getId_cargo());

            ArrayList<Permisos> permisos = usuarioC.getLosPermisos();

            //desmarcar todos por defecto:
            restablecerPermisos();

            //marcar según los permisos del usuario
            for (Permisos p : permisos) {
                switch (p.getId_permiso()) {
                    case 2:
                        venta.setSelected(true);
                        break;
                    case 1:
                        reporte.setSelected(true);
                        break;
                    case 4:
                        cliente.setSelected(true);
                        break;
                    case 3:
                        almacen.setSelected(true);
                        break;
                    case 5:
                        administrar.setSelected(true);
                        break;
                }
            }

        }
    }//GEN-LAST:event_tablaUsersMouseClicked

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        UsuariosDAO ok = new UsuariosDAO();
        if(ok.eliminar(usuarioSelec.getUsuario())){
                JOptionPane.showMessageDialog(rootPane, "Usuario eliminado con éxito", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                restablecerPermisos();
                restablecerTodo();
                llenarTablaUsers();
        }else{
                JOptionPane.showMessageDialog(rootPane, "Usuario no se ha podido eliminar", "Error", JOptionPane.ERROR_MESSAGE);

        }
            
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //actualizar
        llenarTablaUsers();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton administrar;
    private javax.swing.JRadioButton almacen;
    private javax.swing.JLabel botonGoSalir;
    private javax.swing.JComboBox<String> cargo;
    private javax.swing.JRadioButton cliente;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField pass;
    private javax.swing.JRadioButton reporte;
    private javax.swing.JTable tablaUsers;
    private javax.swing.JTextField user;
    private javax.swing.JRadioButton venta;
    // End of variables declaration//GEN-END:variables
}
