/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Aplicacion;
import javax.swing.table.DefaultTableModel; //importando para tener el modelo
import Modelo.Cable;
import ModeloDAO.CablesDAO;
import Modelo.GestRepuestos;
import Modelo.Repuesto;
import java.util.ArrayList;
public class Almacen extends javax.swing.JFrame {

    /**
     * Creates new form AdministracionC
     */
    //Diseno de la tabla
    DefaultTableModel tablaCables = new DefaultTableModel(); //Creando objeto tabla (con el modelo default
    DefaultTableModel tablaRepuestos = new DefaultTableModel();

  
    
    public Almacen() {
        initComponents();
        setLocationRelativeTo(null);
        //animacion botones y tablas:
        opRepuestos.setVisible(false);
        opCables.setVisible(false);
        tablaDeRepuestos.setVisible(false);
        tablaDeCables.setVisible(false);
        jScrollPane2.setVisible(false);
        jScrollPane1.setVisible(false);
        OpcionesCables.setVisible(false);
        OpcionesRepuestos.setVisible(false);
        botonesCables.setVisible(false);
        botonesRepuesto.setVisible(false);
        
        //tabla cables
        String id[] = {"Codigo","Tipo","Marca (Auto)","Modelo (Auto)","Año (Auto)","Cantidad","Marca (Cable)","Precio Unitario Venta" , "Precio Unitario Costo"}; // titulos de la tabla de Cables
        tablaCables.setColumnIdentifiers(id); // Columa(titulo)
        tablaDeCables.setModel(tablaCables); //establece el modelo para tabla cables
        llenarTablaCables(); //subir informacion de cables
        
        //tabla repuestos
        String id2[] = {"Codigo","Tipo","Marca","Cantidad","Tamaño"}; // titulos de la tabla de Cables
        tablaRepuestos.setColumnIdentifiers(id2);
        tablaDeRepuestos.setModel(tablaRepuestos);
        llenarTablaRepuestos();
        




    }
    
        private void llenarTablaCables() {
        // Iterar sobre el arreglo cables y agregar los datos a la tabla
            CablesDAO conex = new CablesDAO();
            ArrayList<Cable>  listaCables = new ArrayList<>();
            listaCables = conex.listarTodos();
        for (int i = 0; i < listaCables.size(); i++) {
            
            Object[] fila = {
                listaCables.get(i).getCodigo(),
                listaCables.get(i).getTipo(), 
                listaCables.get(i).getMarca_auto(), 
                listaCables.get(i).getModelo_auto(),
                listaCables.get(i).getAnio_auto(),
                listaCables.get(i).getCantidad(), 
                listaCables.get(i).getMarcaC(),
                listaCables.get(i).getPrecioUnt(),
                listaCables.get(i).getPrecioCosto()
            };
            tablaCables.addRow(fila); // Agregar la fila al modelo

        }
    }
    
        
        private void llenarTablaRepuestos() {
        // Iterar sobre el arreglo cables y agregar los datos a la tabla
        for (int i = 0; i < GestRepuestos.getRepuestoCont(); i++) {
            Repuesto mirepuesto = GestRepuestos.getRepuestos()[i]; // Obtener el cable actual
            Object[] fila = {
                mirepuesto.getCodigo(), 
                mirepuesto.getTipo(), 
                mirepuesto.getMarca(), 
                mirepuesto.getCantidad(), 
                mirepuesto.getTamano()
            };

            tablaRepuestos.addRow(fila); // Agregar la fila al modelo

        }
    }
            
        private void vaciarTabla(){
            
            tablaCables.setRowCount(0);
            tablaRepuestos.setRowCount(0);
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OpcionesCables = new javax.swing.JPanel();
        BuscarBoton = new javax.swing.JLabel();
        anioAuto = new javax.swing.JTextField();
        marcaCable = new javax.swing.JTextField();
        modeloAuto = new javax.swing.JTextField();
        codigo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tipoCable = new javax.swing.JTextField();
        marcaAuto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        OpcionesRepuestos = new javax.swing.JPanel();
        BuscarR = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tamanoRepuesto = new javax.swing.JTextField();
        tipoRepuesto = new javax.swing.JTextField();
        marcaRepuesto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        botonesCables = new javax.swing.JPanel();
        escasosoGoBotonCables = new javax.swing.JLabel();
        escasosBotonCables = new javax.swing.JLabel();
        pedirGoBotonCables = new javax.swing.JLabel();
        pedirBotonCables = new javax.swing.JLabel();
        botonesRepuesto = new javax.swing.JPanel();
        escasosoGoBotonRepuesto = new javax.swing.JLabel();
        escasosBotonRepuesto = new javax.swing.JLabel();
        pedirGoBotonRepuesto = new javax.swing.JLabel();
        pedirBotonRepuesto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDeRepuestos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaDeCables = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        opRepuestos = new javax.swing.JLabel();
        RepuestosOP = new javax.swing.JLabel();
        opCables = new javax.swing.JLabel();
        CablesOP = new javax.swing.JLabel();
        botonSalir = new javax.swing.JLabel();
        botonGoSalir = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OpcionesCables.setForeground(new java.awt.Color(255, 255, 255));
        OpcionesCables.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BuscarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/lupa_icono.PNG"))); // NOI18N
        BuscarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarBotonMouseClicked(evt);
            }
        });
        OpcionesCables.add(BuscarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, -1, -1));

        anioAuto.setBackground(new java.awt.Color(255, 255, 255));
        anioAuto.setForeground(new java.awt.Color(0, 0, 0));
        anioAuto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        anioAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anioAutoActionPerformed(evt);
            }
        });
        OpcionesCables.add(anioAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 130, -1));

        marcaCable.setBackground(new java.awt.Color(255, 255, 255));
        marcaCable.setForeground(new java.awt.Color(0, 0, 0));
        marcaCable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        OpcionesCables.add(marcaCable, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 130, -1));

        modeloAuto.setBackground(new java.awt.Color(255, 255, 255));
        modeloAuto.setForeground(new java.awt.Color(0, 0, 0));
        modeloAuto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        modeloAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeloAutoActionPerformed(evt);
            }
        });
        OpcionesCables.add(modeloAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 130, -1));

        codigo.setBackground(new java.awt.Color(255, 255, 255));
        codigo.setForeground(new java.awt.Color(0, 0, 0));
        codigo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        OpcionesCables.add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 130, -1));

        jLabel15.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Codigo:");
        OpcionesCables.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, 20));

        jLabel14.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Año de auto:");
        OpcionesCables.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, 20));

        jLabel9.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Marca de cable:");
        OpcionesCables.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, 20));

        jLabel10.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Tipo de cable:");
        OpcionesCables.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, 20));

        jLabel8.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Modelo de auto:");
        OpcionesCables.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, 20));

        jLabel7.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Marca de auto:");
        OpcionesCables.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, 20));

        tipoCable.setBackground(new java.awt.Color(255, 255, 255));
        tipoCable.setForeground(new java.awt.Color(0, 0, 0));
        tipoCable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        OpcionesCables.add(tipoCable, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 130, -1));

        marcaAuto.setBackground(new java.awt.Color(255, 255, 255));
        marcaAuto.setForeground(new java.awt.Color(0, 0, 0));
        marcaAuto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        OpcionesCables.add(marcaAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 130, -1));

        jLabel1.setFont(new java.awt.Font("Sitka Heading", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Busqueda:");
        OpcionesCables.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/diseno/fondoparabotones.PNG"))); // NOI18N
        OpcionesCables.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 615, 110));

        getContentPane().add(OpcionesCables, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 42, 610, 110));

        OpcionesRepuestos.setForeground(new java.awt.Color(255, 255, 255));
        OpcionesRepuestos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BuscarR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/lupa_icono.PNG"))); // NOI18N
        BuscarR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarRMouseClicked(evt);
            }
        });
        OpcionesRepuestos.add(BuscarR, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, -1, -1));

        jLabel11.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Tamaño:");
        OpcionesRepuestos.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        jLabel12.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Tipo de Repuesto:");
        OpcionesRepuestos.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel13.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Marca de Repuesto:");
        OpcionesRepuestos.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        tamanoRepuesto.setBackground(new java.awt.Color(255, 255, 255));
        tamanoRepuesto.setForeground(new java.awt.Color(0, 0, 0));
        tamanoRepuesto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        OpcionesRepuestos.add(tamanoRepuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 137, -1));

        tipoRepuesto.setBackground(new java.awt.Color(255, 255, 255));
        tipoRepuesto.setForeground(new java.awt.Color(0, 0, 0));
        tipoRepuesto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        OpcionesRepuestos.add(tipoRepuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 137, -1));

        marcaRepuesto.setBackground(new java.awt.Color(255, 255, 255));
        marcaRepuesto.setForeground(new java.awt.Color(0, 0, 0));
        marcaRepuesto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        OpcionesRepuestos.add(marcaRepuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 137, -1));

        jLabel5.setFont(new java.awt.Font("Sitka Heading", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Busqueda:");
        OpcionesRepuestos.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/diseno/fondoparabotones.PNG"))); // NOI18N
        OpcionesRepuestos.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 615, 110));

        getContentPane().add(OpcionesRepuestos, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 42, 610, 110));

        botonesCables.setBackground(new java.awt.Color(255, 255, 255));
        botonesCables.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        escasosoGoBotonCables.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/escasosIcono.PNG"))); // NOI18N
        escasosoGoBotonCables.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                escasosoGoBotonCablesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                escasosoGoBotonCablesMouseExited(evt);
            }
        });
        botonesCables.add(escasosoGoBotonCables, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 280, 70));

        escasosBotonCables.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/productosEscasos_Almacen.PNG"))); // NOI18N
        escasosBotonCables.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                escasosBotonCablesMouseEntered(evt);
            }
        });
        botonesCables.add(escasosBotonCables, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, 70));

        pedirGoBotonCables.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/pedirIcono2Administrar.PNG"))); // NOI18N
        pedirGoBotonCables.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pedirGoBotonCablesMouseExited(evt);
            }
        });
        botonesCables.add(pedirGoBotonCables, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 7, -1, -1));

        pedirBotonCables.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/pedirIconoAdministrar.PNG"))); // NOI18N
        pedirBotonCables.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pedirBotonCablesMouseEntered(evt);
            }
        });
        botonesCables.add(pedirBotonCables, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, 70));

        getContentPane().add(botonesCables, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 560, 80));

        botonesRepuesto.setBackground(new java.awt.Color(255, 255, 255));
        botonesRepuesto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        escasosoGoBotonRepuesto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/escasosIcono.PNG"))); // NOI18N
        escasosoGoBotonRepuesto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                escasosoGoBotonRepuestoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                escasosoGoBotonRepuestoMouseExited(evt);
            }
        });
        botonesRepuesto.add(escasosoGoBotonRepuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 280, 70));

        escasosBotonRepuesto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/productosEscasos_Almacen.PNG"))); // NOI18N
        escasosBotonRepuesto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                escasosBotonRepuestoMouseEntered(evt);
            }
        });
        botonesRepuesto.add(escasosBotonRepuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, 70));

        pedirGoBotonRepuesto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/pedirIcono2Administrar.PNG"))); // NOI18N
        pedirGoBotonRepuesto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pedirGoBotonRepuestoMouseExited(evt);
            }
        });
        botonesRepuesto.add(pedirGoBotonRepuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        pedirBotonRepuesto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/pedirIconoAdministrar.PNG"))); // NOI18N
        pedirBotonRepuesto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pedirBotonRepuestoMouseEntered(evt);
            }
        });
        botonesRepuesto.add(pedirBotonRepuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, 70));

        getContentPane().add(botonesRepuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 560, 80));

        tablaDeRepuestos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaDeRepuestos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 570, 240));

        tablaDeCables.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane2.setViewportView(tablaDeCables);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 660, 240));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/gif.gif"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 320, 250));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Elegir opcion");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, -1, -1));

        opRepuestos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/diseno/opcion_almacen_repuestos.PNG"))); // NOI18N
        getContentPane().add(opRepuestos, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 265, 220, 60));

        RepuestosOP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RepuestosOPMouseClicked(evt);
            }
        });
        getContentPane().add(RepuestosOP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 180, 50));

        opCables.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/diseno/opcion_almacen_cables.PNG"))); // NOI18N
        opCables.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opCablesMouseClicked(evt);
            }
        });
        getContentPane().add(opCables, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 206, 220, 60));

        CablesOP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CablesOPMouseClicked(evt);
            }
        });
        getContentPane().add(CablesOP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 180, 50));

        botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/salida_almacen.PNG"))); // NOI18N
        botonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonSalirMouseEntered(evt);
            }
        });
        getContentPane().add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 592, -1, -1));

        botonGoSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonGoSalirMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonGoSalirMouseExited(evt);
            }
        });
        getContentPane().add(botonGoSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 590, 50, 50));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondos/fondo - almacen.PNG"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opCablesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opCablesMouseClicked
        
    }//GEN-LAST:event_opCablesMouseClicked

    private void CablesOPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CablesOPMouseClicked
        opCables.setVisible(true);
        tablaDeCables.setVisible(true);
        opRepuestos.setVisible(false);
        tablaDeRepuestos.setVisible(false);
        jScrollPane2.setVisible(true);
        jScrollPane1.setVisible(false);
        OpcionesCables.setVisible(true);
        OpcionesRepuestos.setVisible(false);
        botonesCables.setVisible(true);
        botonesRepuesto.setVisible(false);
        escasosoGoBotonCables.setVisible(false);
        pedirGoBotonCables.setVisible(false);
        vaciarTabla();
        llenarTablaCables();
    }//GEN-LAST:event_CablesOPMouseClicked

    private void RepuestosOPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RepuestosOPMouseClicked
        opCables.setVisible(false);
        tablaDeCables.setVisible(false);
        opRepuestos.setVisible(true);
        tablaDeRepuestos.setVisible(true);
        jScrollPane1.setVisible(true);
        jScrollPane2.setVisible(false);
        OpcionesCables.setVisible(false);
        OpcionesRepuestos.setVisible(true);
        botonesCables.setVisible(false);
        botonesRepuesto.setVisible(true);
        escasosoGoBotonRepuesto.setVisible(false);
        pedirGoBotonRepuesto.setVisible(false);
        vaciarTabla();
        llenarTablaRepuestos();
    }//GEN-LAST:event_RepuestosOPMouseClicked

    private void BuscarBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarBotonMouseClicked
        vaciarTabla();
        llenarTablaCables(); 
        
        
        for (int i = tablaCables.getRowCount() - 1; i >= 0; i--) { // Recorrer de atrás hacia adelante

                 if (!marcaAuto.getText().equals("")&&!marcaAuto.getText().equalsIgnoreCase((String) tablaCables.getValueAt(i, 2))) { //! negacion
                    tablaCables.removeRow(i); // Eliminar fila que no coincide
                } else if (!modeloAuto.getText().equals("")&&!modeloAuto.getText().equalsIgnoreCase(String.valueOf(tablaCables.getValueAt(i, 3)))) { //! negacion
                    tablaCables.removeRow(i); // Eliminar fila que no coincide
                } else if (!tipoCable.getText().equals("")&&!tipoCable.getText().equalsIgnoreCase((String) tablaCables.getValueAt(i, 1))) { //! negacion
                    tablaCables.removeRow(i); // Eliminar fila que no coincide
                } else if (!marcaCable.getText().equals("")&&!marcaCable.getText().equalsIgnoreCase((String) tablaCables.getValueAt(i, 6))) { //! negacion
                    tablaCables.removeRow(i); // Eliminar fila que no coincide
                } else if (!anioAuto.getText().equals("")&&!anioAuto.getText().equalsIgnoreCase(String.valueOf(tablaCables.getValueAt(i, 4)))) { //! negacion
                    tablaCables.removeRow(i); // Eliminar fila que no coincide
                } else if (!codigo.getText().equals("")&&!codigo.getText().equalsIgnoreCase((String) tablaCables.getValueAt(i, 0))) { //! negacion
                    tablaCables.removeRow(i); // Eliminar fila que no coincide
                }                     
    }
    }//GEN-LAST:event_BuscarBotonMouseClicked

    private void BuscarRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarRMouseClicked
        vaciarTabla();
        llenarTablaRepuestos();
        for (int i = tablaRepuestos.getRowCount() - 1; i >= 0; i--) { // Recorrer de atrás hacia adelante

                 if (!tipoRepuesto.getText().equals("")&&!tipoRepuesto.getText().equalsIgnoreCase((String) tablaRepuestos.getValueAt(i, 1))) { //! negacion
                    tablaRepuestos.removeRow(i); // Eliminar fila que no coincide
                }else if (!marcaRepuesto.getText().equals("")&&!marcaRepuesto.getText().equalsIgnoreCase((String) tablaRepuestos.getValueAt(i, 2))) { //! negacion
                    tablaRepuestos.removeRow(i); // Eliminar fila que no coincide
                } else if (!tamanoRepuesto.getText().equals("")&&!tamanoRepuesto.getText().equalsIgnoreCase((String) tablaRepuestos.getValueAt(i, 4))) { //! negacion
                    tablaRepuestos.removeRow(i); // Eliminar fila que no coincide
                }                 
    }        
    }//GEN-LAST:event_BuscarRMouseClicked

    private void escasosoGoBotonCablesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escasosoGoBotonCablesMouseClicked
            vaciarTabla();
            llenarTablaCables();
            for (int i = tablaCables.getRowCount() - 1; i >= 0; i--) {
                if(Integer.parseInt(tablaCables.getValueAt(i, 5).toString())>2){
                    tablaCables.removeRow(i);
                }
            }
    }//GEN-LAST:event_escasosoGoBotonCablesMouseClicked

    private void escasosoGoBotonRepuestoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escasosoGoBotonRepuestoMouseClicked
            vaciarTabla();
            llenarTablaRepuestos();
            for (int i = tablaRepuestos.getRowCount() - 1; i >= 0; i--) {
                if(Integer.parseInt(tablaRepuestos.getValueAt(i, 3).toString())>2){
                    tablaRepuestos.removeRow(i);
                }
            }
    }//GEN-LAST:event_escasosoGoBotonRepuestoMouseClicked

    private void pedirBotonCablesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pedirBotonCablesMouseEntered

        pedirGoBotonCables.setVisible(true);
    }//GEN-LAST:event_pedirBotonCablesMouseEntered

    private void pedirGoBotonCablesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pedirGoBotonCablesMouseExited
        pedirGoBotonCables.setVisible(false);

    }//GEN-LAST:event_pedirGoBotonCablesMouseExited

    private void escasosBotonCablesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escasosBotonCablesMouseEntered
        escasosoGoBotonCables.setVisible(true);

    }//GEN-LAST:event_escasosBotonCablesMouseEntered

    private void escasosoGoBotonCablesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escasosoGoBotonCablesMouseExited
        escasosoGoBotonCables.setVisible(false);
    }//GEN-LAST:event_escasosoGoBotonCablesMouseExited

    private void escasosBotonRepuestoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escasosBotonRepuestoMouseEntered
        escasosoGoBotonRepuesto.setVisible(true);
    }//GEN-LAST:event_escasosBotonRepuestoMouseEntered

    private void escasosoGoBotonRepuestoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escasosoGoBotonRepuestoMouseExited
        escasosoGoBotonRepuesto.setVisible(false);
    }//GEN-LAST:event_escasosoGoBotonRepuestoMouseExited

    private void pedirBotonRepuestoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pedirBotonRepuestoMouseEntered
        pedirGoBotonRepuesto.setVisible(true);
    }//GEN-LAST:event_pedirBotonRepuestoMouseEntered

    private void pedirGoBotonRepuestoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pedirGoBotonRepuestoMouseExited
        pedirGoBotonRepuesto.setVisible(false);
    }//GEN-LAST:event_pedirGoBotonRepuestoMouseExited

    private void botonSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalirMouseEntered
        botonSalir.setVisible(false);
    }//GEN-LAST:event_botonSalirMouseEntered

    private void botonGoSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGoSalirMouseClicked
        Vista.Ingreso.Ventana_Principal regresar = new Vista.Ingreso.Ventana_Principal();
        regresar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonGoSalirMouseClicked

    private void botonGoSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGoSalirMouseExited
        botonSalir.setVisible(true);
    }//GEN-LAST:event_botonGoSalirMouseExited

    private void modeloAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeloAutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modeloAutoActionPerformed

    private void anioAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anioAutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anioAutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Almacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Almacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Almacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Almacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Almacen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BuscarBoton;
    private javax.swing.JLabel BuscarR;
    private javax.swing.JLabel CablesOP;
    private javax.swing.JPanel OpcionesCables;
    private javax.swing.JPanel OpcionesRepuestos;
    private javax.swing.JLabel RepuestosOP;
    private javax.swing.JTextField anioAuto;
    private javax.swing.JLabel background;
    private javax.swing.JLabel botonGoSalir;
    private javax.swing.JLabel botonSalir;
    private javax.swing.JPanel botonesCables;
    private javax.swing.JPanel botonesRepuesto;
    private javax.swing.JTextField codigo;
    private javax.swing.JLabel escasosBotonCables;
    private javax.swing.JLabel escasosBotonRepuesto;
    private javax.swing.JLabel escasosoGoBotonCables;
    private javax.swing.JLabel escasosoGoBotonRepuesto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField marcaAuto;
    private javax.swing.JTextField marcaCable;
    private javax.swing.JTextField marcaRepuesto;
    private javax.swing.JTextField modeloAuto;
    private javax.swing.JLabel opCables;
    private javax.swing.JLabel opRepuestos;
    private javax.swing.JLabel pedirBotonCables;
    private javax.swing.JLabel pedirBotonRepuesto;
    private javax.swing.JLabel pedirGoBotonCables;
    private javax.swing.JLabel pedirGoBotonRepuesto;
    private javax.swing.JTable tablaDeCables;
    private javax.swing.JTable tablaDeRepuestos;
    private javax.swing.JTextField tamanoRepuesto;
    private javax.swing.JTextField tipoCable;
    private javax.swing.JTextField tipoRepuesto;
    // End of variables declaration//GEN-END:variables
}
