/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Aplicacion;
import javax.swing.table.DefaultTableModel;
import Modelo.GestClientes;
import Modelo.Cliente;
/**
 *
 * @author GoodF
 */
public class Clientes extends javax.swing.JFrame {

    /**
     * Creates new form Clientes
     */
    DefaultTableModel tablaDeClientes = new DefaultTableModel();
    
    public Clientes() {
        initComponents();
        setLocationRelativeTo(null);

        botonProveedores.setVisible(false);
        ProveedoresPanel.setVisible(false);
        String titulos[] = {"Nombre","Dni / Ruc","Codigo de Factura","Cantidad de Articulos","Monto total"};
        tablaDeClientes.setColumnIdentifiers(titulos);
        tablaClientes.setModel(tablaDeClientes);
        llenarTablaClientes();
        
    }
            
        private void llenarTablaClientes() {
        // Iterar sobre el arreglo cables y agregar los datos a la tabla
        for (int i = 0; i < GestClientes.getClienteCont(); i++) {
            Cliente losClientes = GestClientes.getClientes()[i]; // Obtener el cable actual
            Object[] fila = {
                losClientes.getNombre(), 
                losClientes.getRucDni(), 
                losClientes.getNumeroFactura(),  
                losClientes.getCantidadesPedidos(),
                losClientes.getMontoT()
            };

            tablaDeClientes.addRow(fila); // Agregar la fila al modelo

        }
    }
            
        private void vaciarTabla(){
            
            tablaDeClientes.setRowCount(0);

        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonClientes = new javax.swing.JLabel();
        botonProveedores = new javax.swing.JLabel();
        ClientePanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ProveedoresPanel = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        botonGoProveedores = new javax.swing.JLabel();
        botonGoClientes = new javax.swing.JLabel();
        btRegresar = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/diseno/opcion_clientes_client.PNG"))); // NOI18N
        getContentPane().add(botonClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 202, 220, 60));

        botonProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/diseno/opcion_clientes_proved.PNG"))); // NOI18N
        getContentPane().add(botonProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 260, 220, 60));

        ClientePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Lista de Clientes Deudores:");
        ClientePanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaClientes);

        ClientePanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 690, 220));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/cobrarIcono.PNG"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        ClientePanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 100, 90));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondos/fondo unit.PNG"))); // NOI18N
        ClientePanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, 0, 700, 450));

        getContentPane().add(ClientePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 690, 450));

        ProveedoresPanel.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 0));
        jTabbedPane1.setFont(new java.awt.Font("Sitka Heading", 0, 18)); // NOI18N

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondos/fondo unit.PNG"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 0, 780, 390));

        jTabbedPane1.addTab("Proveedor 1", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondos/fondo unit.PNG"))); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -40, -1, -1));

        jTabbedPane1.addTab("Proveedor 2", jPanel3);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondos/fondo unit.PNG"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, -40, -1, -1));

        jTabbedPane1.addTab("Proveedor 3", jPanel1);

        jLabel5.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Lista de Proveedores Actuales:");

        javax.swing.GroupLayout ProveedoresPanelLayout = new javax.swing.GroupLayout(ProveedoresPanel);
        ProveedoresPanel.setLayout(ProveedoresPanelLayout);
        ProveedoresPanelLayout.setHorizontalGroup(
            ProveedoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProveedoresPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(ProveedoresPanelLayout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jLabel5)
                .addContainerGap(216, Short.MAX_VALUE))
        );
        ProveedoresPanelLayout.setVerticalGroup(
            ProveedoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProveedoresPanelLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        getContentPane().add(ProveedoresPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 700, 460));

        botonGoProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonGoProveedoresMouseClicked(evt);
            }
        });
        getContentPane().add(botonGoProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 180, 50));

        botonGoClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonGoClientesMouseClicked(evt);
            }
        });
        getContentPane().add(botonGoClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 180, 50));

        btRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btRegresarMouseClicked(evt);
            }
        });
        getContentPane().add(btRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 580, 50, 50));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondos/fondo - clientes.PNG"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGoProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGoProveedoresMouseClicked
        botonProveedores.setVisible(true);
        ProveedoresPanel.setVisible(true);
        botonClientes.setVisible(false);
        ClientePanel.setVisible(false);
    }//GEN-LAST:event_botonGoProveedoresMouseClicked

    private void botonGoClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGoClientesMouseClicked
        botonClientes.setVisible(true);
        botonProveedores.setVisible(false);
        ClientePanel.setVisible(true);
        ProveedoresPanel.setVisible(false);

    }//GEN-LAST:event_botonGoClientesMouseClicked

    private void btRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRegresarMouseClicked
        Vista.Ingreso.Ventana_Principal regres = new Vista.Ingreso.Ventana_Principal();
        regres.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btRegresarMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        GestClientes.setFactura((String)tablaDeClientes.getValueAt(tablaClientes.getSelectedRow(),2));
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ClientePanel;
    private javax.swing.JPanel ProveedoresPanel;
    private javax.swing.JLabel botonClientes;
    private javax.swing.JLabel botonGoClientes;
    private javax.swing.JLabel botonGoProveedores;
    private javax.swing.JLabel botonProveedores;
    private javax.swing.JLabel btRegresar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tablaClientes;
    // End of variables declaration//GEN-END:variables
}
