/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Aplicacion;

import javax.swing.table.DefaultTableModel;
import ModeloDAO.CablesDAO;
import Modelo.Cable;
import Modelo.Usuarios;
import java.util.ArrayList;
import Seguridad.Sesion;
import Vista.Ingreso.Login;
import javax.swing.JOptionPane;
import Servicios.GeneradorBoleta;

/**
 *
 * @author GoodF
 */
public class ProcesoVenta extends javax.swing.JFrame {

    /**
     * Creates new form Ventas
     */
    DefaultTableModel tablaBusqueda = new DefaultTableModel();
    private String codigo;

    public ProcesoVenta(String codigo) {
        initComponents();
        setLocationRelativeTo(null);
        this.codigo = codigo;
        //verifica usuario
        Usuarios myuser = Sesion.getUsuarioActual();
        if (myuser == null) {
            JOptionPane.showMessageDialog(rootPane, "Error! Ningun Usuario se ha logeado!");
            Login volver = new Login();
            volver.setVisible(true);
            this.dispose();
        }

        String id[] = {"Codigo", "Tipo", "Marca (Auto)", "Modelo (Auto)", "Cantidad", "Marca (cables)", "Precio Unitario"}; // titulos de la tabla de Cables
        tablaBusqueda.setColumnIdentifiers(id); // Columa(titulo)
        miTabla.setModel(tablaBusqueda);
        llenarTablaBusqueda();
    }

    private void llenarTablaBusqueda() {
        CablesDAO conex = new CablesDAO();
        Cable micable = new Cable();
        micable = conex.listarUno(codigo);
        for (int i = 0; i < 1; i++) {
            Object[] fila = {
                micable.getCodigo(),
                micable.getTipo(),
                micable.getMarca_auto(),
                micable.getModelo_auto(),
                micable.getCantidad(),
                micable.getMarcaC(),
                micable.getPrecioUnt()
            };
            tablaBusqueda.addRow(fila); // Agregar la fila al modelo

        }
    }

    private void vaciarTabla() {

        tablaBusqueda.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        montoFinal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        miTabla = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cantidad = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        montoT = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        dni = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        descuento = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        boleta = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        opBuscar = new javax.swing.JLabel();
        botonGoFabricar = new javax.swing.JLabel();
        botonSalida = new javax.swing.JLabel();
        botonGoSalida = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(204, 153, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Procesar compra");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 210, 140));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        montoFinal.setEditable(false);
        montoFinal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Producto:");

        miTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(miTabla);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cantidad:");

        cantidad.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(204, 153, 0));
        jButton1.setText("Cotizar");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Monto:");

        montoT.setEditable(false);
        montoT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Ruc / Dni Cliente:");

        dni.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Descuento %:");

        descuento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        descuento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                descuentoKeyPressed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton1.setText("Factura");

        buttonGroup1.add(boleta);
        boleta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        boleta.setForeground(new java.awt.Color(0, 0, 0));
        boleta.setText("Boleta");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Monto Total:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel1))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(descuento, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(montoT, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(montoFinal)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(dni, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83)
                                .addComponent(jRadioButton1)
                                .addGap(27, 27, 27)
                                .addComponent(boleta)))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(montoT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(descuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(montoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(3, 3, 3)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jRadioButton1)
                    .addComponent(boleta))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 610, 300));

        opBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opBuscarMouseClicked(evt);
            }
        });
        getContentPane().add(opBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 180, 50));

        botonGoFabricar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonGoFabricarMouseClicked(evt);
            }
        });
        getContentPane().add(botonGoFabricar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 160, 50));

        botonSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/salida_almacen.PNG"))); // NOI18N
        botonSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonSalidaMouseEntered(evt);
            }
        });
        getContentPane().add(botonSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 581, -1, -1));

        botonGoSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonGoSalidaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonGoSalidaMouseExited(evt);
            }
        });
        getContentPane().add(botonGoSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 580, 40, 50));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondos/fondo - ventas.PNG"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGoFabricarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGoFabricarMouseClicked

    }//GEN-LAST:event_botonGoFabricarMouseClicked

    private void botonGoSalidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGoSalidaMouseExited
        botonSalida.setVisible(true);
    }//GEN-LAST:event_botonGoSalidaMouseExited

    private void botonGoSalidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGoSalidaMouseClicked
        Vista.Ingreso.Ventana_Principal regresar = new Vista.Ingreso.Ventana_Principal();
        regresar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonGoSalidaMouseClicked

    private void botonSalidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalidaMouseEntered
        botonSalida.setVisible(false);
    }//GEN-LAST:event_botonSalidaMouseEntered

    private void opBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opBuscarMouseClicked

    }//GEN-LAST:event_opBuscarMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CablesDAO conex = new CablesDAO();
        Cable micable = new Cable();
        micable = conex.listarUno(codigo);
        montoT.setText(String.valueOf(micable.getPrecioUnt() * Integer.parseInt(cantidad.getText())));
        if (descuento.getText().trim().isEmpty()) {
            descuento.setText("0");
        }
        double monto = Double.parseDouble(montoT.getText());
        double desc = Double.parseDouble(descuento.getText());
        double total = monto - (monto * (desc / 100));

        montoFinal.setText(String.valueOf(total));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (boleta.isSelected()) {
            try {
                GeneradorBoleta.generarBoletaYGuardarEnArchivo(
                        Sesion.getUsuarioActual().getNombre(),
                        Sesion.getUsuarioActual().getLosCargos().getNombre_Cargo(),
                        codigo,
                        miTabla.getValueAt(0, 6).toString(),
                        cantidad.getText(),
                        descuento.getText(),
                        montoFinal.getText(),
                        dni.getText()
                );
                JOptionPane.showMessageDialog(this, "✅ Boleta Generada exitosamente.");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "❌ Error al generar la boleta: " + e.getMessage());
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "⚠️ La factura no está disponible por el momento.");
        }
        /*
        if(boleta.isSelected()){
        
            GeneradorBoleta.generarBoletaYGuardarEnArchivo(Sesion.getUsuarioActual().getNombre(), Sesion.getUsuarioActual().getLosCargos().getNombre_Cargo(),codigo, miTabla.getValueAt(0, 6).toString(), cantidad.getText(), descuento.getText(), montoFinal.getText(), dni.getText());
            JOptionPane.showMessageDialog(rootPane, "Boleta Generada! Gracias por la compra");
        }else{
            JOptionPane.showMessageDialog(rootPane, "La factura no esta disponible por el momento");
        }*/
    }//GEN-LAST:event_jButton2ActionPerformed

    private void descuentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descuentoKeyPressed

    }//GEN-LAST:event_descuentoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProcesoVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProcesoVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProcesoVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProcesoVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProcesoVenta("hola").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton boleta;
    private javax.swing.JLabel botonGoFabricar;
    private javax.swing.JLabel botonGoSalida;
    private javax.swing.JLabel botonSalida;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cantidad;
    private javax.swing.JTextField descuento;
    private javax.swing.JTextField dni;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable miTabla;
    private javax.swing.JTextField montoFinal;
    private javax.swing.JTextField montoT;
    private javax.swing.JLabel opBuscar;
    // End of variables declaration//GEN-END:variables
}
