/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Aplicacion;
import javax.swing.table.DefaultTableModel;
import ModeloDAO.CablesDAO;
import Modelo.Cable;
import Modelo.Usuarios;
import java.util.ArrayList;
import Seguridad.Sesion;
import Vista.Ingreso.Login;
import javax.swing.JOptionPane;
/**
 *
 * @author GoodF
 */
public class Ventas extends javax.swing.JFrame {

    /**
     * Creates new form Ventas
     */
    DefaultTableModel tablaBusqueda = new DefaultTableModel();
    
    //Variable codigo enviar producto
    private String codigoSelec;
    
    public void setCodigo(String codigo){
        this.codigoSelec = codigo;
    }
    public String getCodigo(){
        return codigoSelec;
    }
    public Ventas() {
        initComponents();
        setLocationRelativeTo(null);
        imagen.setVisible(false);
        opFabricar.setVisible(false);
        Fabricacion.setVisible(false);
        cotizarGoBoton.setVisible(false); //animacion boton
        cotizarGoBusqueda.setVisible(false);
        
        //verifica usuario
        Usuarios myuser = Sesion.getUsuarioActual();
        if (myuser == null) {
            JOptionPane.showMessageDialog(rootPane, "Error! Ningun Usuario se ha logeado!");
            Login volver = new Login();
            volver.setVisible(true);
            this.dispose();
        }
        
        String id[] = {"Codigo","Tipo","Marca (Auto)","Modelo (Auto)","Cantidad","Marca (cables)","Precio Unitario"}; // titulos de la tabla de Cables
        tablaBusqueda.setColumnIdentifiers(id); // Columa(titulo)
        tablaBusquedaD.setModel(tablaBusqueda);
        llenarTablaBusqueda();
    }
    
        private void llenarTablaBusqueda() {
            CablesDAO conex = new CablesDAO();
            ArrayList<Cable>  listaCables = new ArrayList<>();
            listaCables = conex.listarTodos();
            for (int i = 0; i < listaCables.size(); i++) {
            Object[] fila = {
                listaCables.get(i).getCodigo(),
                listaCables.get(i).getTipo(), 
                listaCables.get(i).getMarca_auto(), 
                listaCables.get(i).getModelo_auto(), 
                listaCables.get(i).getCantidad(), 
                listaCables.get(i).getMarcaC(),
                listaCables.get(i).getPrecioUnt()
            };
            tablaBusqueda.addRow(fila); // Agregar la fila al modelo
            
        }
    }
            
        private void vaciarTabla(){
            
            tablaBusqueda.setRowCount(0);
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        tablasBusqueda = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaBusquedaD = new javax.swing.JTable();
        cotizarGoBusqueda = new javax.swing.JLabel();
        cotizarBusqueda = new javax.swing.JLabel();
        imagen = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jFileChooser2 = new javax.swing.JFileChooser();
        Busqueda = new javax.swing.JPanel();
        BuscarBoton = new javax.swing.JLabel();
        marcaCable = new javax.swing.JTextField();
        modeloAuto = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tipoCable = new javax.swing.JTextField();
        marcaAuto = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        botonGoBuscar = new javax.swing.JLabel();
        opBuscar = new javax.swing.JLabel();
        opFabricar = new javax.swing.JLabel();
        botonGoFabricar = new javax.swing.JLabel();
        Fabricacion = new javax.swing.JPanel();
        cotizarGoBoton = new javax.swing.JLabel();
        cotizarBoton = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField4 = new javax.swing.JTextField();
        jSlider1 = new javax.swing.JSlider();
        botonSalida = new javax.swing.JLabel();
        botonGoSalida = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablasBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        tablasBusqueda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaBusquedaD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaBusquedaD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaBusquedaDMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaBusquedaD);

        tablasBusqueda.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 580, 160));

        cotizarGoBusqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/cotizar_icono_Accion.PNG"))); // NOI18N
        cotizarGoBusqueda.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cotizarGoBusquedaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        cotizarGoBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cotizarGoBusquedaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cotizarGoBusquedaMouseExited(evt);
            }
        });
        tablasBusqueda.add(cotizarGoBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        cotizarBusqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/cotizar_icono_ventas.PNG"))); // NOI18N
        cotizarBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cotizarBusquedaMouseEntered(evt);
            }
        });
        tablasBusqueda.add(cotizarBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        getContentPane().add(tablasBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 590, -1));

        imagen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        imagen.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 170, 40));

        jFileChooser2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser2ActionPerformed(evt);
            }
        });
        imagen.add(jFileChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 548, 297));

        getContentPane().add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 570, 310));

        Busqueda.setForeground(new java.awt.Color(255, 255, 255));
        Busqueda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BuscarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/lupa_icono.PNG"))); // NOI18N
        BuscarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarBotonMouseClicked(evt);
            }
        });
        Busqueda.add(BuscarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, -1, -1));

        marcaCable.setBackground(new java.awt.Color(255, 255, 255));
        marcaCable.setForeground(new java.awt.Color(0, 0, 0));
        marcaCable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Busqueda.add(marcaCable, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 130, -1));

        modeloAuto.setBackground(new java.awt.Color(255, 255, 255));
        modeloAuto.setForeground(new java.awt.Color(0, 0, 0));
        modeloAuto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Busqueda.add(modeloAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 130, -1));

        jLabel13.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Marca de cable:");
        Busqueda.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, 20));

        jLabel14.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Tipo de cable:");
        Busqueda.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, 20));

        jLabel15.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Modelo de auto:");
        Busqueda.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, 20));

        jLabel16.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Marca de auto:");
        Busqueda.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, 20));

        tipoCable.setBackground(new java.awt.Color(255, 255, 255));
        tipoCable.setForeground(new java.awt.Color(0, 0, 0));
        tipoCable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Busqueda.add(tipoCable, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 130, -1));

        marcaAuto.setBackground(new java.awt.Color(255, 255, 255));
        marcaAuto.setForeground(new java.awt.Color(0, 0, 0));
        marcaAuto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Busqueda.add(marcaAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 130, -1));

        jLabel17.setFont(new java.awt.Font("Sitka Heading", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Busqueda:");
        Busqueda.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/diseno/fondoparabotones.PNG"))); // NOI18N
        Busqueda.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 615, 110));

        getContentPane().add(Busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 610, 110));

        botonGoBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/diseno/opcion_ventas_buscarcable.PNG"))); // NOI18N
        getContentPane().add(botonGoBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 200, 220, 60));

        opBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opBuscarMouseClicked(evt);
            }
        });
        getContentPane().add(opBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 180, 50));

        opFabricar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/diseno/opcion_ventas_fabricar.PNG"))); // NOI18N
        getContentPane().add(opFabricar, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 258, 220, 60));

        botonGoFabricar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonGoFabricarMouseClicked(evt);
            }
        });
        getContentPane().add(botonGoFabricar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 160, 50));

        Fabricacion.setBackground(new java.awt.Color(255, 255, 255));
        Fabricacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cotizarGoBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/cotizar_icono_Accion.PNG"))); // NOI18N
        cotizarGoBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cotizarGoBotonMouseExited(evt);
            }
        });
        Fabricacion.add(cotizarGoBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 114, -1, -1));

        cotizarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/cotizar_icono_ventas.PNG"))); // NOI18N
        cotizarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cotizarBotonMouseEntered(evt);
            }
        });
        Fabricacion.add(cotizarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 113, -1, -1));

        jLabel1.setFont(new java.awt.Font("Serif", 0, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Ingresar modelo del cable");
        Fabricacion.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Tipo de cable:");
        Fabricacion.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(seleccionar)", "embrague", "cambios", "acelerador", " " }));
        Fabricacion.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Marca de auto:");
        Fabricacion.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        jComboBox2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(seleccionar)", "Toyota", "Hyundai", "Honda", "Chevrolet", "Nissan", "Glory", "Kia", "Subaru", "Susuki", "Volkswagen ", "Mitsubishi", "Renault", " " }));
        Fabricacion.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Modelo de auto:");
        Fabricacion.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Insertar imagen de cable:");
        Fabricacion.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 115, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Cantidad:");
        Fabricacion.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        Fabricacion.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 145, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 102, 204));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Fabricacion.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 94, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Longitud del cable:");
        Fabricacion.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Carrera:");
        Fabricacion.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, -1));
        Fabricacion.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 121, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Tipo de gancho:");
        Fabricacion.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(seleccionar)", "Curvo", "Tipo T", "Doble Ranura", "Tipo Candado" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        Fabricacion.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 145, -1, -1));

        jTextField4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "cm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        Fabricacion.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 86, -1));
        Fabricacion.add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 87, -1));

        getContentPane().add(Fabricacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 600, 260));

        botonSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/salida_almacen.PNG"))); // NOI18N
        botonSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonSalidaMouseEntered(evt);
            }
        });
        getContentPane().add(botonSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 581, -1, -1));

        botonGoSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonGoSalidaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonGoSalidaMouseExited(evt);
            }
        });
        getContentPane().add(botonGoSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 580, 40, 50));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondos/fondo - ventas.PNG"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        imagen.setVisible(false);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        imagen.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonGoFabricarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGoFabricarMouseClicked
        opFabricar.setVisible(true);
        Fabricacion.setVisible(true);
        botonGoBuscar.setVisible(false);
        Busqueda.setVisible(false);
        tablasBusqueda.setVisible(false);
    }//GEN-LAST:event_botonGoFabricarMouseClicked

    private void BuscarBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarBotonMouseClicked
        
        vaciarTabla();
        llenarTablaBusqueda();
        for (int i = tablaBusqueda.getRowCount() - 1; i >= 0; i--) { // Recorrer de atrás hacia adelante

            if (!marcaAuto.getText().equals("")&&!marcaAuto.getText().equalsIgnoreCase((String) tablaBusqueda.getValueAt(i, 2))) { //! negacion
                tablaBusqueda.removeRow(i); // Eliminar fila que no coincide
            }else if (!modeloAuto.getText().equals("")&&!modeloAuto.getText().equalsIgnoreCase((String) tablaBusqueda.getValueAt(i, 3))) { //! negacion
                tablaBusqueda.removeRow(i); // Eliminar fila que no coincide
            } else if (!tipoCable.getText().equals("")&&!tipoCable.getText().equalsIgnoreCase((String) tablaBusqueda.getValueAt(i, 1))) { //! negacion
                tablaBusqueda.removeRow(i); // Eliminar fila que no coincide
            }else if (!marcaCable.getText().equals("")&&!marcaCable.getText().equalsIgnoreCase((String) tablaBusqueda.getValueAt(i, 5))) { //! negacion
                tablaBusqueda.removeRow(i); // Eliminar fila que no coincide
            }
        }
        
    }//GEN-LAST:event_BuscarBotonMouseClicked

    private void opBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opBuscarMouseClicked
        botonGoBuscar.setVisible(true);
        Busqueda.setVisible(true);
        Fabricacion.setVisible(false);
        tablasBusqueda.setVisible(true);
        opFabricar.setVisible(false);
    }//GEN-LAST:event_opBuscarMouseClicked

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void cotizarBotonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cotizarBotonMouseEntered
        cotizarGoBoton.setVisible(true);
    }//GEN-LAST:event_cotizarBotonMouseEntered

    private void cotizarGoBotonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cotizarGoBotonMouseExited
        cotizarGoBoton.setVisible(false);
    }//GEN-LAST:event_cotizarGoBotonMouseExited

    private void cotizarBusquedaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cotizarBusquedaMouseEntered
       cotizarGoBusqueda.setVisible(true);
    }//GEN-LAST:event_cotizarBusquedaMouseEntered

    private void cotizarGoBusquedaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cotizarGoBusquedaMouseExited
        cotizarGoBusqueda.setVisible(false);
    }//GEN-LAST:event_cotizarGoBusquedaMouseExited

    private void jFileChooser2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFileChooser2ActionPerformed

    private void botonGoSalidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGoSalidaMouseExited
        botonSalida.setVisible(true);
    }//GEN-LAST:event_botonGoSalidaMouseExited

    private void botonGoSalidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGoSalidaMouseClicked
        Vista.Ingreso.Ventana_Principal regresar = new Vista.Ingreso.Ventana_Principal();
        regresar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonGoSalidaMouseClicked

    private void botonSalidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalidaMouseEntered
        botonSalida.setVisible(false);
    }//GEN-LAST:event_botonSalidaMouseEntered

    private void cotizarGoBusquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cotizarGoBusquedaMouseClicked
        ProcesoVenta conectar = new ProcesoVenta(getCodigo());
        conectar.setVisible(true);
        this.dispose();
        //**cotizar
    }//GEN-LAST:event_cotizarGoBusquedaMouseClicked

    private void cotizarGoBusquedaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cotizarGoBusquedaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_cotizarGoBusquedaAncestorAdded

    private void tablaBusquedaDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaBusquedaDMouseClicked
               int fila = tablaBusquedaD.getSelectedRow();
        if (fila != -1) {
            DefaultTableModel modelo = (DefaultTableModel) tablaBusquedaD.getModel();

            setCodigo(modelo.getValueAt(fila, 0).toString());
        }
    }//GEN-LAST:event_tablaBusquedaDMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BuscarBoton;
    private javax.swing.JPanel Busqueda;
    private javax.swing.JPanel Fabricacion;
    private javax.swing.JLabel botonGoBuscar;
    private javax.swing.JLabel botonGoFabricar;
    private javax.swing.JLabel botonGoSalida;
    private javax.swing.JLabel botonSalida;
    private javax.swing.JLabel cotizarBoton;
    private javax.swing.JLabel cotizarBusqueda;
    private javax.swing.JLabel cotizarGoBoton;
    private javax.swing.JLabel cotizarGoBusqueda;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel imagen;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField marcaAuto;
    private javax.swing.JTextField marcaCable;
    private javax.swing.JTextField modeloAuto;
    private javax.swing.JLabel opBuscar;
    private javax.swing.JLabel opFabricar;
    private javax.swing.JTable tablaBusquedaD;
    private javax.swing.JPanel tablasBusqueda;
    private javax.swing.JTextField tipoCable;
    // End of variables declaration//GEN-END:variables
}
